### ISSUE TITLE
Add ngld‘s OverlayPlugin support.

### ISSUE THREAD

**Issue by ShadyWhite** [MarbleBag/Gobchat#24]
Add ngld‘s OverlayPlugin support please.

**Comment by MarbleBag** [comment]
I read about ngld's OverlayPlugin, especially because Cactbot uses it too, but instead I'm working on a stand-alone version of the chat. So it becomes a lot easier to install and use. I hope to have a release this or next week.

**Comment by ShadyWhite** [comment]
> I read about ngld's OverlayPlugin, especially because Cactbot uses it too, but instead I'm working on a stand-alone version of the chat. So it becomes a lot easier to install and use. I hope to have a release this or next week.

COOL!
