### ISSUE TITLE
Need a function to reset the position of the overlay

### ISSUE THREAD

**Issue by wanghealerr** [MarbleBag/Gobchat#61]
**Describe the bug**
Overlay windows nowhere to be seen. I disconnected my 4th screen with gobchat on it. After restarting my pc, and reconnecting the display, Gobchat was nowhere to be seen ever since. It's running and functioning correctly in the background, I can even see it in the alt-tab menu. I have windows 10

**Expected behaviour**
Windows right/left/up/down should move the position of the overlay

**Actual behaviour**
Nothing

**Steps to reproduce**
1. Throw gobchat in a secondary screen
2. Disconnect that screen
3. Restart your pc (windows presumably)
4. Reconnect the screen and try to find it

**Additional context**

![image](https://user-images.githubusercontent.com/11689891/112912601-e2070500-90c5-11eb-84db-6b9a99b7ef5d.png)
![image](https://user-images.githubusercontent.com/11689891/112912676-17abee00-90c6-11eb-8418-b2e38f24286c.png)

**Comment by MarbleBag** [comment]
I will look into that. 
For a fast 'fix' close Gobchat and go to `%appdata%\Gobchat\config` and either
- change the name of the config or profile folder. Gobchat will make a new default profile with the overlay at position 0, 0 (top left), after that move the old files into the new folder, restart Gobchat and change the position settings of your old profiles via config dialog

- go into the profile folder and edit your active profile manually (`gobconfig.json` tells you which is the active one) You are looking for `behaviour -> frame -> chat -> position` set x and y to 0
