### ISSUE TITLE
[18:14] [Gobchat] FFXIV Chat kann nicht ausgelesen werden. Starte Gobchat mit Adminrechte. SOS 

### ISSUE THREAD

**Issue by Driemer116** [MarbleBag/Gobchat#63]
**Describe the bug**
Der fehler ist wie folgt. Ich habe denn aktuellen Version geladen aber bekomme immer die gleiche fehler meldung auch wenn ich es als Admin starte.

**Expected behaviour**
Es sollte Chat auslesen und so Narichten anzeigen

**Actual behaviour**
[18:14] [Gobchat] FFXIV Chat kann nicht ausgelesen werden. Starte Gobchat mit Adminrechte.

**Steps to reproduce**
1. Ich starte die neue Version Normal nach dem sie fertig geladen und installiert ist
2. Das Fenster öffnet sich vom chat
3. und zeigt mit dann an [18:14] [Gobchat] FFXIV Chat kann nicht ausgelesen werden. Starte Gobchat mit Adminrechte.
4. Ich schließe es wieder und stelle als Adimistrator ein
5. starte es wieder und bekomme die gleiche fehler meldung nochmal.

**Additional context**
Ich weis nicht was ich noch tun soll und hoffe daher auf hilfe hier seits. Alles genannte steht oben und ist seit denn Patch 5.5 so. Auch nachdem ich Gobchat gobchat-1.10.0-1 installiert habe.

**Comment by Driemer116** [comment]
Übersetzt mit DeepL
Translated with DeepL

Describe the bug
The error is as follows. I have loaded the latest version but I always get the same error message even when I run it as admin.

Expected behaviour
It should read the chat and display the following messages

Actual behaviour
18:14] [Gobchat] FFXIV chat cannot be read. Start Gobchat with admin rights.

Steps to reproduce
Steps to reproduce the behavior:

I start the new version Normal after it is finished loading and installing.
The window opens from chat
and then shows [18:14] [Gobchat] FFXIV chat cannot be read. Start Gobchat with admin rights.
I close it again and set as Adimistrator
start it again and get the same error message again.
Additional context
I don't know what else to do and hope for help from this side. Everything mentioned above is since Patch 5.5 so. Even after I installed Gobchat gobchat-1.10.0-1.

**Comment by MarbleBag** [comment]
Thanks, 5.5 changed some stuff, don't worry, the problem is already resolved.
