### ISSUE TITLE
[ERROR] Group does not support player names

### ISSUE THREAD

**Issue by vsgabrys** [MarbleBag/Gobchat#71]
**Describe the bug**
From the first use, I have not been able to set up groups on GC. When trying to add (or run the remove command) I get the error **Group [1] (symbol) does not support player names.**

Have tried with different groups, using a macro with <t> and manually typing the name, running as admin/not as admin.

**Expected behaviour**
I should be able to add a player to a group

**Actual behaviour**
Error above shows, and am unable to add players to groups.

**Steps to reproduce**
1. Type /e gc group 1 add firstname lastname
2. Press enter
3. See error

**Additional context**
Likely an environmental issue - using Windows 10 64-bit, dx11 - can provide further environmental details if you let me know what you need

![image](https://user-images.githubusercontent.com/91932022/135958988-1ac6c84f-e8d7-4e9f-ba38-9de9be12ea2f.png)

**Comment by MarbleBag** [comment]
Gobchat comes with some predefined groups, these are the same ones you have ingame by assigning a symbol to someone on your friend list. Like a star or circle. These groups are special and basically only act on people with these symbols. 

Characters can only be added to newly created groups. These groups come with an editable text box for character names. I will rephrase the error message to make this more clear to the user.
