### ISSUE TITLE
Can't resize the window or move it without manually typing numbers in settings.

### ISSUE THREAD

**Issue by chrisgreatest** [MarbleBag/Gobchat#75]
**Describe the bug**
I can;t use the mouse to drag or move the chat window. I can however go to settings and type numbers for X and Y position and size and hit Save to change it.

**Expected behaviour**
The wiki says I can click and drag.

**Actual behaviour**
It doesnt click and drag in 6.0.8

**Steps to reproduce**
Install, Run, try to click and drag.

**Additional context**
nothing additional, everything else seems fine but I just wanted this for the extra tabs so I haven't used additional features

**Comment by MarbleBag** [comment]
Dragging and resizing is activated by pressing and holding left-ctrl.
