### ISSUE TITLE
Feature Request: Dual Monitor Mode

### ISSUE THREAD

**Issue by Immanius** [MarbleBag/Gobchat#94]
**Is your feature request related to a problem? Please describe.**
Since GobChat is an overlay, seeing content from w/in the game, such as mouse over popups, can be difficult when it is placed under the chat pane

**Describe the solution you'd like**
While I'm calling this "dual monitor mode" it's really just about allowing the chat pane to not be confined to the FFXIV window. Since most people probably play full screen, this is why i chose that name.
ie: allowing for negative X/Y coords to allow placement of the chat pane outside of the play field.

**Describe alternatives you've considered**
None, or all of the other chat mods (of which there is only like one more serious contender, maybe?) depending on how you want to look at it. Gobchat appears to be the only chat mod that has all of the features I already want.

**Comment by MarbleBag** [comment]
At first, I was pretty sure this should already work! But I checked again to make sure and see there; negative values can't be set via the UI- I will fix that. I guess I missed that, because I only move it around via dragging (press ctrl, now you can move it with your mouse).

**Comment by Immanius** [comment]
... Holy crap I didn't know you could use control to move it around.

**Comment by Immanius** [comment]
you may want to check values that are larger than the monitor as well. I only brought up negative values since my second monitor is on the left.
